version: 2.1

executors:
  python-node:
      docker:
        - image: circleci/python:jessie-node-browsers
      resource_class: small
      
jobs:

  build:
    executor: python-node
    steps:
      - checkout

      - run:
          name: Download Selenium
          command: |
            wget http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
            mkdir test-reports && touch test-reports/selenium.log

      - run:
          name: Download ChromeDriver
          command: |
            wget https://chromedriver.storage.googleapis.com/2.41/chromedriver_linux64.zip
            unzip chromedriver_linux64.zip

      - restore_cache:
          keys:
            - pip-packages-v1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
            - pip-packages-v1-{{ .Branch }}-
            - pip-packages-v1-

      - run:
          name: Install Pip andPython Dependancies
          command: |  
            sudo apt install python3-pip
            sudo pip install pipenv
            pipenv install

      - save_cache:
          paths:
              - ~/.local/share/virtualenvs/venv 
          key: pip-packages-v1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}

      - persist_to_workspace:
          root: .
          paths:
            - selenium-server-standalone-3.5.3.jar
            - test-reports
            - chromedriver
            

  test:
    executor: python-node
    steps:
      - checkout
      - attach_workspace:
          at: .

      - run:
           name: Start Selenium
           command: java -jar selenium-server-standalone-3.5.3.jar 
           background: true

      - run:
           name: Selenium Test
           command: python myTest.py 
    

workflows:
  test-workflow:
    jobs:
      - build
      - test:
         requires:
            - build

