version: 2.1

    steps:
      - checkout
      - run: pip install 
      - run: sudo pip install --upgrade pip
      - run: 
          command: |
            set -x

            sudo curl https://cli-assets.heroku.com/install.sh | sh 
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container: login
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container: push -a demo-app-circleci web
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container: -a push -a demo-app-circleci web
      





